=== abrandwi/logging/logging-log4j2/src/main/resources/messageFormat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2015 Cisco Systems, Inc.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="criterion">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="field" />
			</xsd:sequence>
			<xsd:attribute name="format" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="appender">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="0" ref="criteria" />
			</xsd:sequence>
			<xsd:attribute name="defaultFormat" type="xsd:string" use="required" />
			<xsd:attribute name="id" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="defaultAppender">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="0" ref="criteria" />
			</xsd:sequence>
			<xsd:attribute name="defaultFormat" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="markers">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="log4jMarker" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="field">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string"  use="required"/>
			<xsd:attribute name="equals" type="xsd:string"  use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="log4jMarker">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="defaultAppender" />
				<xsd:element maxOccurs="unbounded" ref="appender" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string"  use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="criteria">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="criterion" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== abrandwi/logging/logging-log4j2/src/test/resources/messageFormat.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright 2014 Cisco Systems, Inc.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->

<markers xsi:noNamespaceSchemaLocation="http://ch-infra.il.nds.com/cabResources/messageFormat.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<marker id="com.cisco.oss.foundation.logging.test.structured.TransactionMarker">
		<defaultAppender defaultFormat="My default format for %u{sourceId} and %u{sourceType} and %u{base}">
			<criteria>
				<criterion format="my conditional format 1 from xml">
					<field name="sourceId" equals="sourceId1" />
					<field name="sourceType" equals="sourceType1" />
				</criterion>
				<criterion format="my conditional format 2 from xml">
					<field name="sourceId" equals="sourceId2" />
					<field name="sourceType" equals="sourceType2" />
				</criterion>
				<criterion format="my conditional format 3 from xml">
					<field name="sourceId" equals="sourceId3" />
					<field name="sourceType" equals="sourceType3" />
				</criterion>
				<criterion format="my conditional format 4 from xml">
					<field name="sourceId" equals="sourceId3" />
					<field name="sourceType" equals="sourceType4" />
				</criterion>
			</criteria>
		</defaultAppender>

		<appender id="logfile" defaultFormat="My default format for %u{sourceId} and %u{sourceType}">
			<criteria>
				<criterion format="my conditional format 1 from xml">
					<field name="sourceId" equals="sourceId1" />
					<field name="sourceType" equals="sourceType1" />
				</criterion>
				<criterion format="my conditional format 2 from xml">
					<field name="sourceId" equals="sourceId2" />
					<field name="sourceType" equals="sourceType2" />
				</criterion>
			</criteria>
		</appender>

		<appender id="auditfile" defaultFormat="My default format for %u{sourceId} and %u{sourceType} and %u{base}">
			<criteria>
				<criterion format="my conditional format 1 from xml - audit">
					<field name="sourceId" equals="sourceId1" />
					<field name="sourceType" equals="sourceType1" />
				</criterion>
			</criteria>
		</appender>

		<appender id="biFile" defaultFormat="My default format for %u{sourceId} and %u{sourceType}" />

	</marker>

	<marker id="TransactionMarker3">
		<defaultAppender defaultFormat="My default format for %u{sourceId} and %u{sourceType}" />

		<appender id="logfile" defaultFormat="My default format for %u{sourceId} and %u{sourceType}">
			<criteria>
				<criterion format=" my conditional format 1 from xml ">
					<field name="sourceId" equals="sourceId1" />
					<field name="sourceType" equals="sourceType1" />
				</criterion>
				<criterion format="my conditional format 2 from xml">
					<field name="sourceId" equals="sourceId2" />
					<field name="sourceType" equals="sourceType2" />
				</criterion>
			</criteria>
		</appender>

		<appender id="auditfile" defaultFormat="My default format for %u{sourceId} and %u{sourceType}">
			<criteria>
				<criterion format="my conditional format 1 from xml">
					<field name="sourceId" equals="sourceId1" />
					<field name="sourceType" equals="sourceType1" />
				</criterion>
			</criteria>
		</appender>

		<appender id="biFile" defaultFormat="My default format for %u{sourceId} and %u{sourceType}" />

	</marker>

<marker id="com.cisco.oss.foundation.logging.test.structured.TransactionMarker2">
		<defaultAppender defaultFormat="My default format for %u{sourceId} and %u{sourceType}" />

		<appender id="logfile" defaultFormat="My default format for %u{sourceId} and %u{sourceType}">
			<criteria>
				<criterion format=" my conditional format 1 from xml ">
					<field name="sourceId" equals="sourceId1" />
					<field name="sourceType" equals="sourceType1" />
				</criterion>
				<criterion format="my conditional format 2 from xml">
					<field name="sourceId" equals="sourceId2" />
					<field name="sourceType" equals="sourceType2" />
				</criterion>
			</criteria>
		</appender>

		<appender id="auditfile" defaultFormat="My default format for %u{sourceId} and %u{sourceType}">
			<criteria>
				<criterion format="my conditional format 1 from xml">
					<field name="sourceId" equals="sourceId1" />
					<field name="sourceType" equals="sourceType1" />
				</criterion>
			</criteria>
		</appender>

		<appender id="biFile" defaultFormat="My default format for %u{sourceId} and %u{sourceType}" />

	</marker>

</markers>
